[package]
name = "rust-timetables"
version = "0.1.0"
authors = ["tomverran <tom@tomverran.co.uk>"]

[dependencies]
ftp = { git = "https://github.com/tomverran/rust-ftp.git" }
xml-rs = "0.3.6"
flate2 = "0.2"
